projects:
  itm:
    schema: ./itm-gql.graphql
    extensions:
      endpoints:
        itm endpoint:
          url: http://localhost:4000/graphql
          introspect: true
    documents: ./src/graphql/itm/**.*