export enum PublishStateEnum {
    LOG_CREATED = 'logCreated',
    USER_CREATED = 'userCreated',
    USER_UPDATED = 'userUpdated',
    USER_DELETED = 'userDeleted',
    USER_LOGOUT = 'userLogout',
    NOTE_CREATED = 'noteCreated',
    NOTE_UPDATED = 'noteUpdated',
    NOTE_DELETED = 'noteDeleted',
    NOTE_CONFIG_CREATED = 'noteConfigCreated',
    NOTE_CONFIG_UPDATED = 'noteConfigUpdated',
    NOTE_CONFIG_UPSERTED = 'noteConfigUpserted',
    TASK_CREATED = 'taskCreated',
    TASK_UPDATED = 'taskUpdated',
    TASK_DELETED = 'taskDeleted',
}
